import { OpsHeader } from "@/app/ops/_components/ops-header";
import { requirePlatformOperator } from "@/lib/auth";
import { listPlatformOperators } from "@/lib/supabase";

export const dynamic = "force-dynamic";

export default async function OpsTeamPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) {
  const operator = await requirePlatformOperator();
  const params = await searchParams;
  const operators = await listPlatformOperators();
  const canEdit = operator.role === "super_admin";
  return <main className="leads-view"><section className="leads-shell"><OpsHeader currentPage="team" operatorEmail={operator.email} /><div className="leads-header"><div><p className="t-eyebrow">Team</p><h1 className="t-display">The people who can move customers.</h1><p className="leads-subtitle">Only super admins can invite, change roles, or revoke access.</p></div></div>{params.error ? <div className="intake-error settings-notice" role="alert">{params.error === "last_super_admin" ? "Keep at least one active super admin." : params.error === "self_revoke" ? "You cannot revoke your own access." : "That team change could not be saved."}</div> : null}<section className="panel setup-panel"><div className="setup-panel__head"><p className="t-eyebrow">Invite</p><h2>Add an operator by email.</h2></div><form action="/api/ops/team" method="post" className="lead-controls"><input type="hidden" name="action" value="invite" /><input className="field" name="email" type="email" placeholder="operator@example.com" required disabled={!canEdit} /><select className="field" name="role" defaultValue="operator" disabled={!canEdit}><option value="operator">Operator</option><option value="support">Support</option><option value="super_admin">Super admin</option></select><button className="btn btn-primary" type="submit" disabled={!canEdit}>Invite</button></form></section><div className="ops-team-list">{operators.map((member) => <article className="panel setup-panel" key={member.userId}><div className="ops-team-row"><div><strong>{member.email || "Unnamed operator"}</strong><small>{member.createdAt ? new Date(member.createdAt).toLocaleDateString() : "Added date unavailable"}</small></div><span className="chip chip-muted">{member.role} · {member.status}</span>{canEdit && member.userId !== operator.userId && member.status === "active" ? <form action="/api/ops/team" method="post"><input type="hidden" name="action" value="revoke" /><input type="hidden" name="user_id" value={member.userId} /><button className="btn btn-ghost btn-sm" type="submit">Revoke</button></form> : null}</div></article>)}</div></section></main>;
}
