"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Lead } from "@/lib/supabase/types";
import { contactEditPatch, contactFromLead, contactRequest, type ContactDetails } from "@/lib/contact-client";
import { ContactEditor } from "@/app/settings/_components/contact-editor";

export function LeadContactControls({ lead, readOnly, onChanged }: { lead: Lead; readOnly: boolean; onChanged: (contact: ContactDetails | null) => void }) {
  const router = useRouter(); const [contact, setContact] = useState(() => contactFromLead(lead)); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const editButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { setContact(contactFromLead(lead)); setEditing(false); }, [lead]);
  function close() { setEditing(false); requestAnimationFrame(() => editButton.current?.focus()); }
  async function action(kind: "suppress_auto_sms" | "mark_personal") { if (busy || readOnly) return; setBusy(true); setNotice(""); try { const result = await contactRequest<{ contact: ContactDetails }>(`/api/leads/${lead.id}/contact`, "POST", { action: kind, contactId: contact?.id ?? null, version: contact?.version ?? null }); setContact(result.contact); onChanged(result.contact); router.refresh(); setNotice(kind === "mark_personal" ? "Marked Personal. History is kept outside business Reports." : "Automatic texts are off for future missed calls."); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not save contact preferences."); } finally { setBusy(false); } }
  async function reverse() { if (!contact || busy || readOnly) return; setBusy(true); setNotice(""); try { const personal = contact.classification === "personal"; const result = await contactRequest<{ contact: ContactDetails }>(`/api/contacts/${contact.id}`, "PATCH", contactEditPatch(contact.version, contact.display_name ?? "", "customer", personal ? "suppress" : "standard")); setContact(result.contact); onChanged(result.contact); router.refresh(); setNotice(personal ? "Marked as Business. Automatic texts remain off until enabled." : "Automatic texts are on for future missed calls."); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not save contact preferences."); } finally { setBusy(false); } }
  if (lead.id.startsWith("sample-")) return null;
  return <section className="lead-contact-controls" aria-label="Contact preferences"><div className="contact-heading"><p className="t-eyebrow">Contact preferences</p><div className="contact-heading__actions">{!readOnly && !editing ? <><button className="btn btn-secondary btn-sm" disabled={busy || contact?.classification === "personal"} onClick={() => contact?.auto_sms_policy === "standard" ? void action("suppress_auto_sms") : void reverse()}>{contact?.auto_sms_policy === "standard" ? "Turn off automatic texts" : "Turn on automatic texts"}</button><button className="btn btn-secondary btn-sm" disabled={busy} onClick={() => contact?.classification === "personal" ? void reverse() : void action("mark_personal")}>{contact?.classification === "personal" ? "Mark as business" : "Mark as personal"}</button></> : null}{!readOnly ? <button ref={editButton} type="button" className="btn btn-ghost btn-sm" aria-expanded={editing} onClick={() => { if (editing) close(); else { setEditing(true); setNotice(""); } }}>Edit contact preferences</button> : null}</div></div>{notice ? <p role="status">{notice}</p> : null}{editing && !readOnly ? <ContactEditor key={contact ? `${contact.id}:${contact.version}` : lead.id} contact={contact} phone={lead.phone} onCancel={close} onSaved={(saved) => { setContact(saved); onChanged(saved); router.refresh(); close(); setNotice(saved ? "Contact preferences saved." : "Contact removed. Future calls follow standard rules."); }} onStale={() => { close(); router.refresh(); }} /> : null}</section>;
}
